name: lint dbt project on push

on:
  push:
    branches-ignore:
      - 'main'

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}

jobs:
  # this job runs SQLFluff with a specific set of rules
  # note the dialect is set to Snowflake, so make that specific to your setup
  # details on linter rules: https://docs.sqlfluff.com/en/stable/rules.html
  lint_project:
    name: Run SQLFluff linter
    runs-on: ubuntu-latest
  
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"

      - name: convert snowflake private key to file
        env:
          SNOWFLAKEPRIVATEKEY: ${{ secrets.SNOWFLAKEPRIVATEKEY }}
        run: |
          echo "$SNOWFLAKEPRIVATEKEY" > snowflake_private_key.p8

      - name: Generate profiles.yml
        env:
          SNOWFLAKEPRIVATEKEYPASSPHRASE: ${{ secrets.SNOWFLAKEPRIVATEKEYPASSPHRASE }}
          SNOWFLAKEACCOUNT: ${{ secrets.SNOWFLAKEACCOUNT }}
        run: python3 $GITHUB_WORKSPACE/scripts/generate_dbt_profile.py $SNOWFLAKEACCOUNT "$GITHUB_WORKSPACE/snowflake_private_key.p8" $SNOWFLAKEPRIVATEKEYPASSPHRASE

      - name: Install dbt-snowflake
        run: "pip install dbt-snowflake"

      - name: run dbt deps
        run: "dbt deps"

      - name: Install SQLFluff
        run: "pip install sqlfluff==3.0.3"

      - name: install sqlfluff dbt template
        run: "pip install sqlfluff-templater-dbt"

      - name: Lint project
        run: "sqlfluff lint models --dialect snowflake"
